name: RSI Notifier

on:
  schedule:
    - cron: "*/5 * * * *"  # jalan tiap 5 menit
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Hitung RSI dan Kirim ke ntfy
        run: |
          curl -s "https://api.binance.com/api/v3/klines?symbol=BTCFDUSD&interval=1m&limit=100" -o data.json

          prices=($(jq -r '.[][4]' data.json))

          gain=0
          loss=0

          for ((i=${#prices[@]}-7; i<${#prices[@]}-1; i++)); do
            diff=$(echo "${prices[i+1]} - ${prices[i]}" | bc -l)
            if (( $(echo "$diff > 0" | bc -l) )); then
              gain=$(echo "$gain + $diff" | bc -l)
            else
              loss=$(echo "$loss - $diff" | bc -l)
            fi
          done

          avgGain=$(echo "$gain / 6" | bc -l)
          avgLoss=$(echo "$loss / 6" | bc -l)

          if (( $(echo "$avgLoss == 0" | bc -l) )); then
            rsi=100
          else
            rs=$(echo "$avgGain / $avgLoss" | bc -l)
            rsi=$(echo "100 - (100 / (1 + $rs))" | bc -l)
          fi

          rsiFmt=$(printf "%.2f" $rsi)

          curl -X POST -d "RSI 6 (1m) BTC/FDUSD: $rsiFmt" https://ntfy.sh/A
